name: Lint-Test-Build
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5
      - name: Installing the Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Installing Dependencies
        run: npm ci
      - name: Running Lint
        run: npm run lint:fix
  Test:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5
      - name: Installing the Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Installing Dependencies
        run: npm ci
      - name: Testing
        run : npm test 
  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v5
      - name: Installing Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Installing Dependencies
        run: npm ci
      - name: Building the App
        run: npm run build 
      
      
    
